apiVersion: apps/v1
kind: Deployment
metadata:
  name: cato-nodejs
  labels:
    app: cato
    ATO: "CATO-08252020"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cato
  template:
    metadata:
      labels:
        app: cato
        ATO: "CATO-08252020"
    spec:
      containers:
      - name: cato-nodejs
        image: jshark2010/cato-app-nodejs-v1:5
        ports:
        - containerPort: 3000
