pipeline {
  environment {
    nodejsimage = "nswccd-cato-app-nodejs"
    registry = "jshark2010"
    registryCredential = 'dockerhub'

  }
  agent any

  stages {

    stage('Clone another repository to subdir') {
      steps {
        sh 'rm cato-tools -rf; mkdir cato-tools'
        dir ('cato-tools') {
          git branch: 'master',
            credentialsId: 'cato-tools',
            url: 'git@github.com:jcspigler2010/cato-tools.git'
        }
      }
    }

    stage('Check if subdirectory exists') {
      steps{
        sh 'ls -al'
      }
    }

    stage('Building nodejs') {
      steps{
        script {
          dockerImageNodeJs = docker.build("$registry/$nodejsimage:$BUILD_NUMBER", "-f ./app/nodejs/Dockerfile ./app/nodejs")
          nodejsImageid = dockerImageNodeJs.imageName()
        }
      }
    }
    stage('Scan nodejs image') {
      steps{
        prismaCloudScanImage ca: '',
        cert: '',
        dockerAddress: 'unix:///var/run/docker.sock',
        image: "$nodejsImageid",
        key: '',
        logLevel: 'info',
        podmanPath: '',
        project: '',
        resultsFile: "$nodejsimage-$BUILD_NUMBER-prisma-cloud-scan-results.json",
        ignoreImageBuildTime:true
      }

    }

    stage('Publish nodejs results results') {
      steps{
        prismaCloudPublish resultsFilePattern: "$nodejsimage-$BUILD_NUMBER-prisma-cloud-scan-results.json"
      }
    }

    stage('Test Powershell'){
      steps{
       powershell 'Write-Output "Hello, World!"'
     }
    }
    //
    // stage('CATO-collection query Powershell Script') {
    //   steps{
    //     powershell label: 'CATO-Collection Powershell', script: 'cato-tools/PublicSector/PrismaCloudCompute/Continuous_Authority_to_Operate/CATO-collection_query.ps1 ATO:ATO-NSWCCD-CATO-APP jonathan@clearshark.com "clearshark123!" "https://twistlock-console.oceast.cloudmegalodon.us"'
    //   }
    // }
    //
    // stage('Export POAM') {
    //   steps{
    //     sh 'python3 cato-tools/reporting/exportPoam-0.1.3.py -c https://twistlock-console.oceast.cloudmegalodon.us -u jonathan@clearshark.com -p clearshark123! -o "ATO:ATO-NSWCCD-CATO-APP" -id "" -t scans -m reporting/POAM_Export_Sample.xlsx -eu "Jonathan Spigler" -a "cato-app"'
    //   }
    // }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImageNodeJs.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry/$nodejsimage:$BUILD_NUMBER"
      }
    }
  }
  post {
        always {
            archiveArtifacts artifacts: '*.xlsx', onlyIfSuccessful: true
        }
    }
}
